sonar.projectKey=cloudopshub-theepicbook
sonar.projectName=CloudOpsHub - TheEpicBook
sonar.sources=theepicbook/
sonar.exclusions=theepicbook/node_modules/**,theepicbook/public/assets/js/materialize*
sonar.javascript.lcov.reportPaths=theepicbook/coverage/lcov.info
sonar.sourceEncoding=UTF-8
